### ISSUE TITLE
Suggesting removal of Jetpack deprecated hook `jetpack_is_post_mailable`

### ISSUE THREAD

**Issue by TremiDkhar** [a8cteam51/safety-net#116]
#### Description

The hook `jetpack_is_post_mailable` used in the file [includes/common.php:9](https://github.com/a8cteam51/safety-net/blob/trunk/includes/common.php#L9) is [deprecated](https://developer.jetpack.com/hooks/jetpack_is_post_mailable/#user-notes).

**Comment by NickGreen** [comment]
Related: https://github.com/a8cteam51/safety-net/issues/106

**Comment by NickGreen** [comment]
Removed here: https://github.com/a8cteam51/safety-net/pull/118
