### ISSUE TITLE
AutomateWoo Plugin

### ISSUE THREAD

**Issue by kimclow** [a8cteam51/safety-net#124]
Hello! As an action item from the [Taika AutomateWoo Incident](https://to51.wordpress.com/2024/06/27/after-action-report-accidental-emails-sent-from-taikas-staging-site/), we'd like to explore adding some rules for AutomateWoo within Safety Net. 

AutomateWoo does not get disabled when we `Deactivate Plugins` (which is fine), but can we have it turn off all workflows and scrub the queue and scheduled actions?

**Comment by nate-allen** [comment]
Resolved in #128
