### ISSUE TITLE
Disconnect Passport plugin 

### ISSUE THREAD

**Issue by stronenv** [a8cteam51/safety-net#136]
Can we scrub the Client ID and Client Secret for [passport-wp](https://github.com/libatomic/passport-wp)? This will disconnect the WordPress site with the remote Passport instance and stop any accidental data sync between the two.

**Comment by Ninodevo** [comment]
Hey @stronenv this has been implemented in [PR](https://github.com/a8cteam51/safety-net/pull/138).
