### ISSUE TITLE
Research new Woo custom tables

### ISSUE THREAD

**Issue by nate-allen** [a8cteam51/safety-net#64]
WooCommerce will soon have new custom tables. We need to do research on how Safety Net will work with it.

**Comment by NickGreen** [comment]
Database schema post here: https://developer.woocommerce.com/2022/09/15/high-performance-order-storage-database-schema/

Here are the 4 tables new tables we should purge:

`$wpdb->prefix.'wc_orders'`
`$wpdb->prefix.'wc_order_addresses'`
`$wpdb->prefix.'wc_order_operational_data'`
`$wpdb->prefix.'wc_orders_meta'`

So, we'll probably need to check if they exist, and just empty them if so.

**Comment by NickGreen** [comment]
Fixed with https://github.com/a8cteam51/safety-net/pull/72
