### ISSUE TITLE
"New User Registration" email was sent

### ISSUE THREAD

**Issue by marktmcgrath** [a8cteam51/safety-net#70]
We received a report that a "New User Registration" email was received but the expectation is that Safety Net would block this email.

Could this be related to https://github.com/a8cteam51/safety-net/issues/69?

**Comment by nate-allen** [comment]
@NickGreen looks like in WordPress 5.7 there was a new hook added called `pre_wp_mail` that can be used to short circuit email being sent. We should probably be using that. 

That doesn't really explain why the email was sent though. The "to" was definitely unset. But maybe there's some other logic in WordPress that will send the email to the admin if there is no "to" specified? I'm still trying to figure that out.

**Comment by NickGreen** [comment]
Should be fixed here https://github.com/a8cteam51/safety-net/pull/71
