### ISSUE TITLE
Question: Should WP Mail Log logs be deleted?

### ISSUE THREAD

**Issue by jessLundie** [a8cteam51/safety-net#79]
Currently, logs created by WP Mail Log are not scrubbed for data or removed when Safety Net runs. These logs are effectively a cache of customer emails connected to order information and purchase history. Example screenshot from a local copy of a partner site post-scrub, all emails intact:

![image](https://user-images.githubusercontent.com/39742956/215137833-d32650b7-333c-47cf-9f7a-036014d1fdef.png)

Should we be checking for and removing these logs when we remove user data? Also, thinking about potentially Follow Ups, and other plugins that might have logging that contains user data.

**Comment by NickGreen** [comment]
Deleting all WP Mail Logging logs in https://github.com/a8cteam51/safety-net/pull/92
