### ISSUE TITLE
Blocking HubSpot Emails or deactivating the plugin or resetting the connection.

### ISSUE THREAD

**Issue by ErikSolveson** [a8cteam51/safety-net#86]
[In a recent issue](https://woothemes.zendesk.com/agent/tickets/6184933) we discovered the SafetyNet does not currently handle the **HubSpot All-In-One Marketing - Forms, Popups, Live Chat** Plugin's email. As a low-priority improvement could SN implement a way to ether:
- Block Email sent from the plugin (the original issue was that an Event Host received a communication with instructions on how to share the event)
- Deactivate the plugin automatically (the plugin is currently deactivated on dev sites manually).
- Reset the connection (This was an option inside the plugin that disconnects the HubSpot account from that particular WordPress Site.) 

I've included these three since I wasn't sure which would be easiest. I think blocking the emails would probably be best since that addresses the actual issue and if we only deactivate the plugin an unknowing TAM might accidentally enable it again in the future and inadvertently send many emails. 

Thank you,

**Comment by NickGreen** [comment]
Added plugin to denylist and scrubbing access key in https://github.com/a8cteam51/safety-net/pull/92
